### ISSUE TITLE
'Document' object has no attribute 'is_untitled'

### ISSUE THREAD

**Issue by BillyCroan** [seanh/gedit-autoname#4]
When I try to install this plugin, it seems to not do anything.  When I run gedit from terminal, I see this error:
Traceback (most recent call last):
  File "/home/me/.local/share/gedit/plugins/gedit-autoname/autoname/plugin.py", line 33, in tab_added
    self.maybe_set_name(tab.get_document())
  File "/home/me/.local/share/gedit/plugins/gedit-autoname/autoname/plugin.py", line 42, in maybe_set_name
    if not document.is_untitled():
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Document' object has no attribute 'is_untitled'

**Comment by skopz356** [comment]
I fixed this issue in this PR. https://github.com/seanh/gedit-autoname/pull/5

**Comment by BillyCroan** [comment]
This seems to work for me on Gedit 44.2 on Debian bookworm current.   Thank you by the way.  You made gedit a much better editor!
